version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crest-website-gatsby-dev
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    environment:
      - NODE_ENV=development

